spring.application.name=EmployeeManagement
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://ep-spring-breeze-ahrx7aij-pooler.c-3.us-east-1.aws.neon.tech/employeecrud?sslmode=require
createDatabaseIfNotExist=true
spring.datasource.username=neondb_owner
spring.datasource.password=npg_pI4vXPEF1caZ

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.generate_statistics=true
server.port=8080
